services:
  - type: pgsql
    name: mzizination-db
    plan: starter
    ipAllowList: []

  - type: web
    name: mzizination-casino
    env: php
    phpVersion: 8.2
    buildCommand: "sh scripts/build.sh"
    
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_NAME
        value: Mzizination
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: APP_URL
        value: https://mzizination2.onrender.com
      - key: APP_TIMEZONE
        value: Africa/Nairobi
      - key: APP_LOCALE
        value: en
      
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: mzizination-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: mzizination-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: mzizination-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: mzizination-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: mzizination-db
          property: password
      
      - key: CACHE_DRIVER
        value: array
      - key: SESSION_DRIVER
        value: cookie
      - key: QUEUE_DRIVER
        value: sync
      - key: BROADCAST_DRIVER
        value: log
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: debug
    
    plan: starter
    numInstances: 1
    preDeployCommand: "sh scripts/pre-deploy.sh"
